#hall
hall.id=1
hall.privateIp=192.168.200.1
hall.rpcPort=7030

global.zookeeperUrl=192.168.200.1:2181
global.profile=jzy

#mongodb 游戏数据
hall.mongodb.url=mongodb://admin:123456@192.168.200.1:27017
hall.mongodb.database=game-hall


